In [1]:
import numpy as np

# Basic of numpy 

In [2]:
a = np.arange(3,99,7)
a

array([ 3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94])

In [3]:
np.linspace(22,1511, num=67) # creating a array of specific numbers

array([  22.        ,   44.56060606,   67.12121212,   89.68181818,
        112.24242424,  134.8030303 ,  157.36363636,  179.92424242,
        202.48484848,  225.04545455,  247.60606061,  270.16666667,
        292.72727273,  315.28787879,  337.84848485,  360.40909091,
        382.96969697,  405.53030303,  428.09090909,  450.65151515,
        473.21212121,  495.77272727,  518.33333333,  540.89393939,
        563.45454545,  586.01515152,  608.57575758,  631.13636364,
        653.6969697 ,  676.25757576,  698.81818182,  721.37878788,
        743.93939394,  766.5       ,  789.06060606,  811.62121212,
        834.18181818,  856.74242424,  879.3030303 ,  901.86363636,
        924.42424242,  946.98484848,  969.54545455,  992.10606061,
       1014.66666667, 1037.22727273, 1059.78787879, 1082.34848485,
       1104.90909091, 1127.46969697, 1150.03030303, 1172.59090909,
       1195.15151515, 1217.71212121, 1240.27272727, 1262.83333333,
       1285.39393939, 1307.95454545, 1330.51515152, 1353.07575

In [4]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [5]:
x

array([[1, 2],
       [3, 4]])

In [6]:
y

array([[5, 6]])

In [7]:
x.shape

(2, 2)

In [8]:
y.shape

(1, 2)

In [9]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
x1 = np.reshape(y, shape=(2,1), order='C')
x1

array([[5],
       [6]])

In [11]:
x1.shape

(2, 1)

In [12]:
m = np.concatenate((x,x1), axis=1)
m

array([[1, 2, 5],
       [3, 4, 6]])

In [13]:
np.reshape(m, shape=(6,1), order='F')

array([[1],
       [3],
       [2],
       [4],
       [5],
       [6]])

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
f5 = (a>5)|(a==5)

In [16]:
f5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
b = np.nonzero(a<6)
b

(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 0]))

In [18]:
cc = list(zip(a[0],a[1],a[2]))
for cord in cc:
    print(cord)

(np.int64(1), np.int64(5), np.int64(9))
(np.int64(2), np.int64(6), np.int64(10))
(np.int64(3), np.int64(7), np.int64(11))
(np.int64(4), np.int64(8), np.int64(12))


In [19]:
(a[b])

array([1, 2, 3, 4, 5])

In [20]:
# Stacking of arrays 
a1 = ([[1,1],[2,2]])
a2 = ([[3,3],[4,4]])

In [21]:
np.vstack((a1,a2)) # axis 0/ vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [22]:
np.hstack((a1,a2)) # axis 1/ horizontally 

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## split funtion

In [23]:
sf = np.arange(1,31).reshape(3,10)
sf

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [24]:
np.hsplit(sf,5) # split method only work if the number of time you want to split is equal to elements per dimension

[array([[ 1,  2],
        [11, 12],
        [21, 22]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26]]),
 array([[ 7,  8],
        [17, 18],
        [27, 28]]),
 array([[ 9, 10],
        [19, 20],
        [29, 30]])]

In [25]:
np.vsplit(sf,3) # there are only three rows here so we can only spit it into 3.

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]

In [26]:
# split from a specific point 
np.hsplit(sf,(5,9)) # its gonna cut it from 5th and 9th column

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[ 6,  7,  8,  9],
        [16, 17, 18, 19],
        [26, 27, 28, 29]]),
 array([[10],
        [20],
        [30]])]

In [27]:
np.vsplit(sf,(1,2)) # only got 3 rows here.... :)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]

## Slicing an array 

In [28]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [29]:
b1 = a[0,:]
b1[2]=21

In [30]:
a

array([[ 1,  2, 21,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# create a copy if you not want to change anything in the original array 
b2 = a.copy()

In [32]:
b2[2,1]=34
b2

array([[ 1,  2, 21,  4],
       [ 5,  6,  7,  8],
       [ 9, 34, 11, 12]])

In [33]:
a

array([[ 1,  2, 21,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**see it changed the value in the copy but the orginal is same**

## Basic mathematics functions 

In [34]:
a = np.array([[1,3,5,7],[2,4,6,8]])
b = np.array([[5,6,7,8,],[8,7,6,5]])

In [38]:
a+b # sum of 2 arrays

array([[ 6,  9, 12, 15],
       [10, 11, 12, 13]])

In [42]:
b.sum() # sum of all elements in an array 

np.int64(52)

In [43]:
a.sum(axis=0) # sum of columns 

array([ 3,  7, 11, 15])

In [49]:
a.min() # looking for the minimum value in an array 

np.int64(1)

In [48]:
b.max(axis=1) # to check maximum value in a specific axis 

array([8, 8])

In [61]:
c = np.array([[3,3,3,3]])

In [62]:
a+c

array([[ 4,  6,  8, 10],
       [ 5,  7,  9, 11]])

In [84]:
r1 = np.random.default_rng()   # array of random float numbers 
rng.random((7,3,1))

array([[[0.25760046],
        [0.77356069],
        [0.53732021]],

       [[0.83653187],
        [0.16871452],
        [0.28497593]],

       [[0.9093358 ],
        [0.74722942],
        [0.19554972]],

       [[0.88511678],
        [0.96748972],
        [0.60404543]],

       [[0.24191802],
        [0.24446669],
        [0.48770147]],

       [[0.04323529],
        [0.80242133],
        [0.33106145]],

       [[0.24058899],
        [0.46711144],
        [0.8900165 ]]])

In [89]:
rng.integers(6, size=(3,4,3))

array([[[0, 4, 2],
        [5, 4, 1],
        [0, 2, 0],
        [2, 5, 1]],

       [[5, 0, 4],
        [4, 3, 2],
        [1, 3, 3],
        [4, 1, 4]],

       [[2, 0, 3],
        [3, 3, 4],
        [4, 3, 4],
        [0, 2, 4]]])

## Sorting an array 

In [92]:
arr = np.array([[11,11,11, 111, 111, 111, 111, 1333, 1333, 12, 12, 12, 12, 12, 12,7, 7, 7, 776,67,76]])
arr

array([[  11,   11,   11,  111,  111,  111,  111, 1333, 1333,   12,   12,
          12,   12,   12,   12,    7,    7,    7,  776,   67,   76]])

In [98]:
arr_uni=np.unique(arr) # Sorting unique elements in an array 
arr_uni

array([   7,   11,   12,   67,   76,  111,  776, 1333])

In [103]:
# We can check the indices of the unique values 
np.unique(arr, return_index=True)

(array([   7,   11,   12,   67,   76,  111,  776, 1333]),
 array([15,  0,  9, 19, 20,  3, 18,  7]))

In [105]:
# we can also count the numbers of an elements in an array
np.unique(arr , return_counts=True)

(array([   7,   11,   12,   67,   76,  111,  776, 1333]),
 array([3, 3, 6, 1, 1, 4, 1, 2]))

## Changing/ Reversing arays

In [108]:
r = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
rr = np.flip(r)
rr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [111]:
# We can reverse row wise  or column wise 

np.flip(r, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [112]:
np.flip(r,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [120]:
# we can change 1 specific row or column as well

r[1]=np.flip(r[1])
r

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [122]:
r[:,1]=np.flip(r[:,1])

In [123]:
r

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])